version: '3'

services:
  app:
    depends_on:
      - database
    container_name: challenge-dc
    tty: true
    stdin_open: true
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/challenge-dc
      - app-gems:/app-gems
    environment:
      RAILS_ENV: development

  database:
    image: postgres:12.1
    volumes:
      - my-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  my-db:
  app-gems: 