default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] || "rails_development" %>
  username: <%= ENV['DATABASE_USER'] || "postgres" %>
  password: <%= ENV['DATABASE_PASSWORD'] || "postgres" %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  host: database
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: delivery_ruby_development

test:
  <<: *default
  database: delivery_ruby_test

production:
  <<: *default
  database: delivery_ruby_production
